name: "Bug Report"
description: "Report a bug in the project"
labels: ["Bug"]
title: "Bug:: [Short Description]" # Pre-filled title
body:
  - type: textarea
    id: bug_report
    attributes:
      label: "Bug Report"
      description: "Describe the bug, reproduction steps, and related issues."
      value: |
        ## 🐛 Bug Report  
        <!-- Describe the bug concisely -->

        ## Steps to Reproduce  
        <!-- List steps to reproduce the issue -->

        ## Expected Behavior  
        <!-- What should happen? -->

        ## Actual Behavior  
        <!-- What actually happens? -->

        ## Related Issues  
        <!-- Mention any related issues or PRs -->
    validations:
      required: true
