name: "Feature Request"
description: "Request a new feature or improvement"
labels: []
title: "Feature:: [Short Description]" # Pre-filled title
body:
  - type: textarea
    id: feature_request
    attributes:
      label: "Feature Request"
      description: "Describe the feature request and related issues."
      value: |
        ## ✨ Feature Request  
        <!-- Describe the feature in detail -->

        ## Why is this needed?  
        <!-- Explain the value this feature brings -->

        ## Implementation Details  
        <!-- Provide any relevant details on how this could be implemented -->

        ## Related Issues  
        <!-- Mention any related issues or PRs -->
    validations:
      required: true
