name: "Setup Issue"
description: "Issues related to project setup or configuration"
labels: ["Setup"]
title: "Setup:: [Short Description]" # Pre-filled title
body:
  - type: textarea
    id: setup_issue
    attributes:
      label: "Setup Issue"
      description: "Describe the setup issue, reproduction steps, and related issues."
      value: |
        ## ⚙️ Setup Issue  
        <!-- Describe the issue related to setup or configuration -->

        ## Steps to Reproduce  
        <!-- Describe how to reproduce the issue -->

        ## Expected Behavior  
        <!-- What should happen? -->

        ## Actual Behavior  
        <!-- What actually happens? -->

        ## Related Issues  
        <!-- Mention any related issues or PRs -->
    validations:
      required: true
